package com.example.entity;

import com.example.entity.TbTest01;
import com.example.entity.TbTest01Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTest01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    long countByExample(TbTest01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int deleteByExample(TbTest01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int insert(TbTest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int insertSelective(TbTest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    List<TbTest01> selectByExample(TbTest01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    TbTest01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int updateByExampleSelective(@Param("record") TbTest01 record, @Param("example") TbTest01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int updateByExample(@Param("record") TbTest01 record, @Param("example") TbTest01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int updateByPrimaryKeySelective(TbTest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test01
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    int updateByPrimaryKey(TbTest01 record);
}