package com.example.entity;

public class TbTest01 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test01.id
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test01.name
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test01.id
     *
     * @return the value of tb_test01.id
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test01.id
     *
     * @param id the value for tb_test01.id
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test01.name
     *
     * @return the value of tb_test01.name
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test01.name
     *
     * @param name the value for tb_test01.name
     *
     * @mbg.generated Wed Aug 15 14:09:27 GMT+09:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}